version: &version 2.1

###############################
# Templates

scala_211: &scala_211 2.11.12
scala_212: &scala_212 2.12.8
scala_213: &scala_213 2.13.0-M5

settings: &settings
  working_directory: ~/monix
  resource_class: medium

env: &env
  SBT_VERSION: 1.2.8
  SBT_OPTIONS: -J-Xmx2048m -J-XX:MaxMetaspaceSize=512m

executors:
  openjdk8: &openjdk8
    <<: [*settings]
    docker:
      - image: openjdk:8
    environment:
      <<: *env

###############################

commands:
  build:
    parameters:
      scala_version:
        type: string
      command:
        type: string
      target:
        type: string

    steps:
      - run:
          name: Install dependencies
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt git
            curl -sL https://deb.nodesource.com/setup_10.x | bash -
            apt-get install -y nodejs
            apt-get clean && apt-get autoclean

      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: monix-cache-<< parameters.scala_version >>-<< parameters.target >>

      - run:
          name: Compile and test project for Scala << parameters.scala_version >> / << parameters.target >>
          working_directory: ~/monix
          command: cat /dev/null | sbt $SBT_OPTIONS ++<< parameters.scala_version >> << parameters.command >>

      - save_cache:
          key: monix-cache-<< parameters.scala_version >>-<< parameters.target >>
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

###############################

jobs:
  # Scala 2.11, OpenJDK 8

  scala2_11_jvm:
    executor: openjdk8
    steps:
      - build:
          scala_version: *scala_211
          target: JVM
          command: ci-jvm-mima

  scala2_11_js:
    executor: openjdk8
    steps:
      - build:
          scala_version: *scala_211
          target: Javascript
          command: ci-js

  # Scala 2.12, OpenJDK 8

  scala2_12_jvm:
    executor: openjdk8
    steps:
      - build:
          scala_version: *scala_212
          target: JVM
          command: ci-jvm-all

  scala2_12_js:
    executor: openjdk8
    steps:
      - build:
          scala_version: *scala_212
          target: Javascript
          command: ci-js

  # Scala 2.13, OpenJDK 8

  scala2_13_jvm:
    executor: openjdk8
    steps:
      - build:
          scala_version: *scala_213
          target: JVM
          command: ci-jvm

  scala2_13_js:
    executor: openjdk8
    steps:
      - build:
          scala_version: *scala_213
          target: Javascript
          command: ci-js

###############################

workflows:
  version: *version

  test:
    jobs:
      - scala2_11_jvm
      - scala2_11_js
      - scala2_12_jvm
      - scala2_12_js
      - scala2_13_jvm
      - scala2_13_js
