# N.B. with 2.1 the webhook notification no longer works
version: 2.0

shared: &shared
  working_directory: ~/monix
  resource_class: medium
  steps:
    - run:
      name: Install dependencies
      command: |
        apt update && apt install -y curl
        curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
        dpkg -i sbt-$SBT_VERSION.deb
        rm sbt-$SBT_VERSION.deb
        apt-get update
        apt-get install -y sbt python-pip git
        curl -sL https://deb.nodesource.com/setup_10.x | bash -
        apt-get install -y nodejs
        apt-get clean && apt-get autoclean

      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: monix-cache

      - run:
          name: Compile and test project
          working_directory: ~/monix
          command: cat /dev/null | sbt -J-Xmx3584m -J-XX:MaxMetaspaceSize=512m ++$SCALA_VERSION $COMMAND

      - save_cache:
          key: monix-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

jobs:
  java-8-scala-2.11-jvm:
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.2.8
      SCALA_VERSION: 2.11.12
      COMMAND: ci-jvm-mima
    <<: *shared

  java-8-scala-2.11-js:
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.2.8
      SCALA_VERSION: 2.11.12
      COMMAND: ci-js
    <<: *shared

  java-8-scala-2.12-jvm:
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.2.8
      SCALA_VERSION: 2.12.8
      COMMAND: ci-jvm-all
    <<: *shared

  java-8-scala-2.12-js:
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.2.8
      SCALA_VERSION: 2.12.8
      COMMAND: ci-js
    <<: *shared

notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/f1a7ec8fc9a34c6a9108
