# N.B. with 2.1 the webhook notification no longer works
version: 2.1

jobs:
  build:
    working_directory: ~/monix
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.2.8
      SBT_OPTIONS: -J-Xmx3072m -J-XX:MaxMetaspaceSize=1024m
    resource_class: medium
    steps:
      - run:
          name: Install dependencies
          command: |
                    apt update && apt install -y curl
                    curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
                    dpkg -i sbt-$SBT_VERSION.deb
                    rm sbt-$SBT_VERSION.deb
                    apt-get update
                    apt-get install -f -y
                    apt-get install -y python-pip git
                    curl -sL https://deb.nodesource.com/setup_10.x | bash -
                    apt-get install -y nodejs
                    apt-get clean && apt-get autoclean

      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: monix-cache

      - run:
          name: Compile project
          working_directory: ~/monix
          command: cat /dev/null | sbt $SBT_OPTIONS +clean +test:compile +package

      - save_cache:
          key: monix-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

  test_jvm:
    # Can this be shared?
    working_directory: ~/monix
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.2.8
      SBT_OPTIONS: -J-Xmx3072m -J-XX:MaxMetaspaceSize=1024m -J-Xmax-classfile-name
    resource_class: medium
    # ------
    steps:
      - run:
          name: Tests for the JVM
          working_directory: ~/monix
          command: cat /dev/null | sbt $SBT_OPTIONS +coreJVM/test

workflows:
  version: 2
  test_jvm:
    jobs:
      - build
      - test_jvm:
          requires:
            - build

# notify:
#   webhooks:
#     - url: https://webhooks.gitter.im/e/f1a7ec8fc9a34c6a9108
