version: &version 2.1

###############################
# Templates

settings: &settings
  working_directory: ~/monix
  resource_class: medium

env: &env
  SBT_VERSION: 1.2.8
  SBT_OPTIONS: -J-Xmx3072m -J-XX:MaxMetaspaceSize=1024m

executors:
  scala_212: &scala_212
    <<: [*settings]
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      <<: *env
      SCALA_VERSION: 2.12.8

  scala_211: &scala_211
    <<: [*settings]
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      <<: *env
      SCALA_VERSION: 2.11.12

  scala_212_jdk11:
    <<: [*scala_212]
    docker:
      - image: circleci/openjdk:11-jdk

  scala_211_jdk11:
    <<: [*scala_211]
    docker:
      - image: circleci/openjdk:11-jdk

###############################
# Commands

commands:
  build:
    parameters:
      build-steps:
        description: "build steps"
        type: steps
        default: []

    steps:
      - run:
          name: Install dependencies
          command: |-
            echo "Installing SBT version: $SBT_VERSION"
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -f -y
            apt-get install -y python-pip git
            curl -sL https://deb.nodesource.com/setup_10.x | bash -
            apt-get install -y nodejs
            apt-get clean && apt-get autoclean

      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: monix-cache

      - run:
          name: Compile project
          working_directory: ~/monix
          command: cat /dev/null | sbt $SBT_OPTIONS ++$SCALA_VERSION clean test:compile package

      - steps: << parameters.build-steps >>
      - save_cache:
          key: monix-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

###############################
# Jobs

jobs:
  install_dependencies_openjdk8:
    executor: scala_212
    steps:
      - build

  install_dependencies_openjdk11:
    executor: scala_212_jdk11
    steps:
      - build

###############################

workflows:
  version: *version

  "Test Scala 2.11 on OpenJDK 8":
    jobs:
      - install_dependencies_openjdk8

  "Test Scala 2.12 on OpenJDK 8":
    jobs:
      - install_dependencies_openjdk8

#jobs:
#  build_openjdk_8_scala_212:
#    <<: [*settings]
#
#    docker:
#      - image: openjdk:8
#    environment:
#      <<: *env
#      SCALA_VERSION: 2.12.8
#
#    steps:
#      - run:
#          name: Install dependencies
#          command: |
#                    apt update && apt install -y curl
#                    curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
#                    dpkg -i sbt-$SBT_VERSION.deb
#                    rm sbt-$SBT_VERSION.deb
#                    apt-get update
#                    apt-get install -f -y
#                    apt-get install -y python-pip git
#                    curl -sL https://deb.nodesource.com/setup_10.x | bash -
#                    apt-get install -y nodejs
#                    apt-get clean && apt-get autoclean
#
#      - checkout
#      - restore_cache:
#          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
#          key: monix-cache
#
#      - run:
#          name: Compile project
#          working_directory: ~/monix
#          command: cat /dev/null | sbt $SBT_OPTIONS +clean +test:compile +package
#
#      - save_cache:
#          key: monix-cache
#          paths:
#            - "~/.ivy2/cache"
#            - "~/.sbt"
#            - "~/.m2"
#
#  test_openjdk8_jvm:
#    # Can this be shared?
#    working_directory: ~/monix
#    docker:
#      - image: openjdk:8
#    environment:
#      SBT_VERSION: 1.2.8
#      SBT_OPTIONS: -J-Xmx3072m -J-XX:MaxMetaspaceSize=1024m -J-XX:ReservedCodeCacheSize=1024m
#    resource_class: medium
#    # ------
#    steps:
#      - run:
#          name: Tests for the JVM (OpenJDK 8)
#          working_directory: ~/monix
#          command: cat /dev/null | sbt $SBT_OPTIONS +coreJVM/test -J-XX:ReservedCodeCacheSize=1024m
#
#  test_openjdk8_js:
#    # Can this be shared?
#    working_directory: ~/monix
#    docker:
#      - image: openjdk:8
#    environment:
#      SBT_VERSION: 1.2.8
#      SBT_OPTIONS: -J-Xmx3072m -J-XX:MaxMetaspaceSize=1024m  -J-XX:ReservedCodeCacheSize=1024m
#    resource_class: medium
#    # ------
#    steps:
#      - run:
#          name: Tests for JavaScript / Node.js (OpenJDK 8)
#          working_directory: ~/monix
#          command: cat /dev/null | sbt $SBT_OPTIONS +coreJS/test
#
#workflows:
#  version: 2
#  test_openjdk8_jvm:
#    jobs:
#      - build_openjdk_8
#      - test_openjdk8_jvm:
#          requires:
#            - build_openjdk_8
#      - test_openjdk8_js:
#          requires:
#            - build_openjdk_8

# notify:
#   webhooks:
#     - url: https://webhooks.gitter.im/e/f1a7ec8fc9a34c6a9108
