name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: jdk-${{ matrix.java }} scala-${{ matrix.scala }} platform-${{ matrix.platform }} tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Java 8, Scala 2.11, JVM
          - java: 8
            scala: 2.11.12
            command: ci-jvm-mima

          # Java 8, Scala 2.11, JavaScript
          - java: 8
            scala: 2.11.12
            scalaJS: 0.6.32
            command: ci-js

          # Java 8, Scala 2.12, JVM
          - java: 8
            scala: 2.12.11
            command: ci-jvm

          # Java 8, Scala 2.12, JavaScript 0.6.x
          - java: 8
            scala: 2.12.11
            command: ci-js
            scalaJS: 0.6.32            
            
          # Java 8, Scala 2.12, JavaScript 0.6.x
          - java: 8
            scala: 2.12.11
            command: ci-js
            scalaJS: 1.0.0            
            
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.${{ matrix.java }}"
          
      - name: Cache SBT Coursier directory
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-

      - name: Cache SBT directory
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: |
            ${{ runner.os }}-sbt-${{ hashFiles('project/build.properties') }}-${{ hashFiles('project/plugins.sbt') }}
          restore-keys: ${{ runner.os }}-sbt-
          
      - name: Run Tests for Java ${{ matrix.java }}, Scala ${{ matrix.scala }}, JS ${{matrix.scalaJS:-default}}, ${{ matrix.command }}
        run: |
          ./.github/scripts/build
        env:
          SBT_COMMAND: ${{ matrix.command }}
          SCALA_VERSION: ${{ matrix.scala }}
          SCALAJS_VERSION: ${{ matrix.scalaJS }}
